# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import file_system_pb2 as file__system__pb2

GRPC_GENERATED_VERSION = '1.67.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in file_system_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FileSystemStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UploadFile = channel.unary_unary(
                '/FileSystem/UploadFile',
                request_serializer=file__system__pb2.FileRequest.SerializeToString,
                response_deserializer=file__system__pb2.FileResponse.FromString,
                _registered_method=True)
        self.DownloadFile = channel.unary_unary(
                '/FileSystem/DownloadFile',
                request_serializer=file__system__pb2.FileRequest.SerializeToString,
                response_deserializer=file__system__pb2.FileResponse.FromString,
                _registered_method=True)
        self.DeleteFile = channel.unary_unary(
                '/FileSystem/DeleteFile',
                request_serializer=file__system__pb2.FileRequest.SerializeToString,
                response_deserializer=file__system__pb2.FileResponse.FromString,
                _registered_method=True)
        self.ListFiles = channel.unary_unary(
                '/FileSystem/ListFiles',
                request_serializer=file__system__pb2.ListRequest.SerializeToString,
                response_deserializer=file__system__pb2.FileListResponse.FromString,
                _registered_method=True)
        self.GetFileInfo = channel.unary_unary(
                '/FileSystem/GetFileInfo',
                request_serializer=file__system__pb2.FileRequest.SerializeToString,
                response_deserializer=file__system__pb2.FileMetadata.FromString,
                _registered_method=True)
        self.SyncDirectory = channel.unary_stream(
                '/FileSystem/SyncDirectory',
                request_serializer=file__system__pb2.DirectoryRequest.SerializeToString,
                response_deserializer=file__system__pb2.FileStatus.FromString,
                _registered_method=True)
        self.GetHealth = channel.unary_unary(
                '/FileSystem/GetHealth',
                request_serializer=file__system__pb2.HealthRequest.SerializeToString,
                response_deserializer=file__system__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.RegisterWorker = channel.unary_unary(
                '/FileSystem/RegisterWorker',
                request_serializer=file__system__pb2.WorkerRegistration.SerializeToString,
                response_deserializer=file__system__pb2.WorkerRegistrationResponse.FromString,
                _registered_method=True)
        self.UnregisterWorker = channel.unary_unary(
                '/FileSystem/UnregisterWorker',
                request_serializer=file__system__pb2.WorkerUnregistration.SerializeToString,
                response_deserializer=file__system__pb2.WorkerUnregistrationResponse.FromString,
                _registered_method=True)


class FileSystemServicer(object):
    """Missing associated documentation comment in .proto file."""

    def UploadFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DownloadFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListFiles(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFileInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SyncDirectory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetHealth(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterWorker(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnregisterWorker(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FileSystemServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UploadFile': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadFile,
                    request_deserializer=file__system__pb2.FileRequest.FromString,
                    response_serializer=file__system__pb2.FileResponse.SerializeToString,
            ),
            'DownloadFile': grpc.unary_unary_rpc_method_handler(
                    servicer.DownloadFile,
                    request_deserializer=file__system__pb2.FileRequest.FromString,
                    response_serializer=file__system__pb2.FileResponse.SerializeToString,
            ),
            'DeleteFile': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteFile,
                    request_deserializer=file__system__pb2.FileRequest.FromString,
                    response_serializer=file__system__pb2.FileResponse.SerializeToString,
            ),
            'ListFiles': grpc.unary_unary_rpc_method_handler(
                    servicer.ListFiles,
                    request_deserializer=file__system__pb2.ListRequest.FromString,
                    response_serializer=file__system__pb2.FileListResponse.SerializeToString,
            ),
            'GetFileInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFileInfo,
                    request_deserializer=file__system__pb2.FileRequest.FromString,
                    response_serializer=file__system__pb2.FileMetadata.SerializeToString,
            ),
            'SyncDirectory': grpc.unary_stream_rpc_method_handler(
                    servicer.SyncDirectory,
                    request_deserializer=file__system__pb2.DirectoryRequest.FromString,
                    response_serializer=file__system__pb2.FileStatus.SerializeToString,
            ),
            'GetHealth': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHealth,
                    request_deserializer=file__system__pb2.HealthRequest.FromString,
                    response_serializer=file__system__pb2.HealthResponse.SerializeToString,
            ),
            'RegisterWorker': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterWorker,
                    request_deserializer=file__system__pb2.WorkerRegistration.FromString,
                    response_serializer=file__system__pb2.WorkerRegistrationResponse.SerializeToString,
            ),
            'UnregisterWorker': grpc.unary_unary_rpc_method_handler(
                    servicer.UnregisterWorker,
                    request_deserializer=file__system__pb2.WorkerUnregistration.FromString,
                    response_serializer=file__system__pb2.WorkerUnregistrationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'FileSystem', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('FileSystem', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FileSystem(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def UploadFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FileSystem/UploadFile',
            file__system__pb2.FileRequest.SerializeToString,
            file__system__pb2.FileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DownloadFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FileSystem/DownloadFile',
            file__system__pb2.FileRequest.SerializeToString,
            file__system__pb2.FileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FileSystem/DeleteFile',
            file__system__pb2.FileRequest.SerializeToString,
            file__system__pb2.FileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListFiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FileSystem/ListFiles',
            file__system__pb2.ListRequest.SerializeToString,
            file__system__pb2.FileListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFileInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FileSystem/GetFileInfo',
            file__system__pb2.FileRequest.SerializeToString,
            file__system__pb2.FileMetadata.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SyncDirectory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/FileSystem/SyncDirectory',
            file__system__pb2.DirectoryRequest.SerializeToString,
            file__system__pb2.FileStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetHealth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FileSystem/GetHealth',
            file__system__pb2.HealthRequest.SerializeToString,
            file__system__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterWorker(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FileSystem/RegisterWorker',
            file__system__pb2.WorkerRegistration.SerializeToString,
            file__system__pb2.WorkerRegistrationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnregisterWorker(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FileSystem/UnregisterWorker',
            file__system__pb2.WorkerUnregistration.SerializeToString,
            file__system__pb2.WorkerUnregistrationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
